-- Investing is not spending.
--
-- Every Coinbase buy was being recorded as an expense and every sell as
-- income, so trading the same money back and forth inflated both sides
-- enormously — 96% of all money "moving through" this app was crypto
-- trading volume, which made every budget, savings rate, chart and total
-- meaningless.
--
-- The `type` column is constrained to income/expense and is relied on
-- everywhere, so rather than widen it, this adds an explicit flag. Rows
-- marked here are excluded from budgeting math and shown in their own
-- Investments section instead — nothing is deleted, it's just filed
-- where it belongs.
alter table transactions
  add column if not exists exclude_from_budget boolean not null default false;

create index if not exists idx_transactions_exclude_from_budget
  on transactions(user_id, exclude_from_budget);

-- Backfill: everything that came from a Coinbase export. These titles are
-- generated by the importer in a consistent "Coinbase <action> <asset>"
-- shape, plus the relabelled "Coinbase Transfer" rows.
update transactions
set exclude_from_budget = true
where title ilike 'Coinbase %';
